version: "3"

services:
  database:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ${STORAGE_DATABASE}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  cache:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

  nextcloud:
    image: nextcloud:26-fpm-alpine
    restart: always
    depends_on:
      - database
      - cache
    volumes:
      - ${STORAGE_USERDATA}:/var/www/html/data
      - ${STORAGE_NEXTCLOUD}:/var/www/html
    links:
      - database
      - cache
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: cache
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      SMTP_HOST: ${MAIL_SMTP_HOST}
      SMTP_SECURE: ${MAIL_SMTP_SECURE}
      SMTP_PORT: ${MAIL_SMTP_PORT}
      SMTP_AUTHTYPE: ${MAIL_SMTP_AUTHTYPE}
      SMTP_NAME: ${MAIL_SMTP_NAME}
      SMTP_PASSWORD: ${MAIL_SMTP_PASSWORD}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_DOMAIN: ${MAIL_DOMAIN}

  proxy:
    image: caddy:alpine
    restart: unless-stopped
    depends_on:
      - nextcloud
    ports:
      - 80:80
      - 90:90
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - ${STORAGE_CADDYDATA}:/data
      - ${STORAGE_CADDYCONFIG}:/config
    volumes_from:
      - nextcloud
